### ISSUE TITLE
Class 'Grav\Plugin\Problems\desktop.ini' not found

### ISSUE THREAD

**Issue by yankl** [getgrav/grav-plugin-problems#32]
I'm developing a Grav site locally on my Windows 10 computer. 

I often get this error message instead of a useful error message when, e.g., I make a syntax error. For instance, when I had the following line in a twig file: 

`{% set film = page.media|filter(i => i matches '/(m|M)ovie')|first  %}`
(where I accidentally forgot the ending slash for the regex)

I get the above error message: Class 'Grav\Plugin\Problems\desktop.ini' not found. 

However, if I disable the "problems" plugin by adding an underscore to the folder name in user/plugins, renaming it "problems_", and reload, I get the much more useful error message: 

An exception has been thrown during the rendering of a template ("preg_match(): No ending delimiter '/' found").

I tried deleting a few desktop.ini files here and there, but do not know which one is being referred to, and couldn't figure how to resolve the issue in any other way. 

Plugin version: 2.0.3

**Comment by rhukster** [comment]
Super weird that theer's a `desktop.ini` reference there.

**Comment by yankl** [comment]
If it helps, this is where it's pointing to: 

![image](https://user-images.githubusercontent.com/425828/114615456-65bc1680-9cae-11eb-90f0-ab378574e63f.png)

**Comment by mahagr** [comment]
Should be fixed in v2.1.1, though.. I have no idea why your problems plugin folder has desktop.ini file in it.
