### ISSUE TITLE
v1.3.1 false-positives non-executable bin files

### ISSUE THREAD

**Issue by le717** [getgrav/grav-plugin-problems#4]
Once I installed Grav on my site this morning I installed and updated various plugins, including Problems. After lunch I was greeted to a Problems page saying everything in the bin/ folder was not executable. It seemed as if the site broke itself in a half-hour. Long-story short, I traced it to the Problems v1.3.1 update.

The issue is all the bin files _are_ executable. Despite the error message preventing site access, I was able to use the admin panel plugin and run them in the command-line.

I suspect the false-positive is from my server upgrades. I manually installed PHP 7.0.0 from https://launchpad.net/~ondrej/+archive/ubuntu/php-7.0. For some reason I cannot run the scripts as written in the documentation (`bin/grav`) but must prefix them with `php` (`php bin/grav`). I've tried installing `php7.0-cli` but it won't work for some reason. Other than that Grav fully works with no errors (that I know of).

So yea. That's the bug report. Hopefully a fix can be devised. :)

`php -v` dump:
```
PHP 7.0.0-5+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by le717** [comment]
Apologies! I clicked enter by mistake. :( Sorry about that. I have a issue to file but I did not mean to submit it just yet!

**Comment by le717** [comment]
Alright, sorry about that. I didn't mean to submit the issue prematurely. It's all written up now. :)

**Comment by apxwn** [comment]
Same problem here. XAMPP on Windows.
First thing I noticed, that the directory of the apparently non-executable files was rendered with //bin (two slashes).
Anyhow, removing the leading slash from `$dir = new \DirectoryIterator(ROOT_DIR . '/bin');` in `problems.php` didn't help.
I commented out the whole "Execute permissions" section - this helps for now.

**Comment by rhukster** [comment]
I'll shall check this logic again to see if I can improve it.

of note, if you have to 'prefix' your `bin/grav` command with `php` then that leads me to think the scripts are not executable as the message is reporting.  You are basically just feeding the file into the executable `php` command.

**Comment by apxwn** [comment]
To reproduce the double slash problem:
- clear cache
- rename the bin directory so the system can't find it.

Here's my output:
```0 - DirectoryIterator::__construct(D:/Programme/Xampp/htdocs/litera//bin,D:/Programme/Xampp/htdocs/litera//bin): The system cannot find the file specified. (code: 2)```

**Comment by rhukster** [comment]
Yah that does have a double slash, and:

```
$dir = new \DirectoryIterator(ROOT_DIR . 'bin');
```

Produces the correct path, however, it does not change the problem.   For some reason the `$file->isExecutable()`  check s failing.  Can you give me a dump of your file permissions?

eg:

```
> ls -la
total 2336
drwxr-xr-x   6 rhuk  staff      204 Dec  3 18:06 .
drwxrwxr-x  30 rhuk  staff     1020 Dec  7 16:46 ..
-rwxr-xr-x   1 rhuk  staff  1181186 Nov 23 16:36 composer.phar
-rwxr-xr-x   1 rhuk  staff     1640 Dec  3 18:06 gpm
-rwxr-xr-x   1 rhuk  staff     1434 Oct 23 17:57 grav
-rwxr-xr-x   1 rhuk  staff     3656 Dec  1 13:13 plugin
```

**Comment by apxwn** [comment]
```
gpm                1691 user   group   rw-r-----   Dec 08 17:10
grav               1434 user   group   rw-r-----   Dec 08 17:10		
composer.phar   1181186	user   group   rw-r-----   Dec 08 17:10		
plugin             3656 user   group   rw-r-----   Dec 08 17:10
```
I can see that they're not marked executable. Can't tell why.

**Comment by rhukster** [comment]
Hmmm clearly this check won't work on windows, i'll have to add a check for to skip it on windows.

**Comment by rhukster** [comment]
Ok 1.3.2 should be live pretty soon.. It has a check to skip the permissions test for windows platforms.

BTW, if problems is giving you a _problem_ (no pun intended) you can either disable it or remove/uninstall it.  it's meant to help people fix their broken installations, but if your install is working fine, you really don't need it.

**Comment by rhukster** [comment]
btw, to fix the executable permissions simple do this:

```
cd bin
chmod +x *
```

**Comment by apxwn** [comment]
Thank you!

The permissions dump with non-executables in /bin was done from a (probably non-Windows) live host running Apache via FTP. Didn't have the executable check fail there though the files were (are!) still not marked executable. (Can do the chmod thing, of course.)

**Comment by rhukster** [comment]
The best way to migrate from windows to a linux host is to not simply copy the whole site up there, rather install Grav directly on the server, then simply copy the `user/` folder from your local windows to remote linux site.

This way you will not have any permission issues plus the copy/sync will be much faster because there's going to be a lot less files involved.

**Comment by le717** [comment]
Apologies for the silence, I've been away from my laptop all day (I'm currently on mobile). I probably won't be able to try out your suggestions until tomorrow evening. Sorry about that. :(

**Comment by le717** [comment]
@rhukster I was able to test out your commands this evening. You were right, the executable bit was missing. I'm not why I was confusing Grav working when I view a page vs running a tool on the command-line (I think I was tired). Sorry about that. I've updated the plugin and revised the permissions. It all works now. Thanks. :smile: 

I'll let you close this issue. ;)
