### ISSUE TITLE
V1.0.4, files in /bin/ are not executable

### ISSUE THREAD

**Issue by alex1236** [getgrav/grav-plugin-problems#5]
I decided to try this out on my free account at hostinger.co.uk when I open the site, I see the following screen: http://vgy.me/7GlKNc.png Those 4 files inside of /bin/ are the only ones I'm having issues with, my permissions are set like this: http://vgy.me/dCkiRK.png I have no idea why this is, the only thing I can think of is it may be because I am running on a free hosting service but I sincerely doubt it.

**Comment by rhukster** [comment]
Can you not SSH to the server and actually check via an `ls -la` ?

```
[06:03:02] $ ls -la
total 1180
drwxrwxr-x  2 rocket rocket    4096 Dec  8 15:00 .
drwxr-xr-x 12 rocket rocket    4096 Dec  8 15:00 ..
-rwxrwxr-x  1 rocket rocket 1181186 Dec  8 15:00 composer.phar
-rwxrwxr-x  1 rocket rocket    1640 Dec  8 15:00 gpm
-rwxrwxr-x  1 rocket rocket    1434 Aug 25 23:12 grav
-rwxrwxr-x  1 rocket rocket    3656 Dec  8 15:00 plugin
```

**Comment by alex1236** [comment]
I'm not able to SSH into the server.

**Comment by alex1236** [comment]
I'm not able to SSH in

**Comment by alex1236** [comment]
I'm currently trying this on my desktop running abyss web server X1, I'll let you know how it goes.

**Comment by rhukster** [comment]
Never heard of that webserver so it's going to be unsupported at this time.
