### ISSUE TITLE
Changing PHP requirements 404

### ISSUE THREAD

**Issue by locii** [getgrav/grav-plugin-problems#6]
When running a lesser version of PHP this warning comes in the problems page:

Your PHP version (5.4.4) is lower than the minimum required: 5.5.9 - Additional Information

The link links to this page:
http://getgrav.org/blog/changing-php-requirements-to-5.5

But it's a 404.

Tried to see where the correct page is but couldn't find it to fix it.

**Comment by rhukster** [comment]
Yah we know :) We're going to add that page tomorrow.

**Comment by locii** [comment]
Ah ha no sweat :)
