### ISSUE TITLE
Devtools - fails

### ISSUE THREAD

**Issue by rbwilkinson** [getgrav/grav-plugin-problems#7]
I tired to use Devtools on CLI. I get this error:

PHP Fatal error:  Cannot redeclare static Grav\Console\ConsoleCommand::$grav as non static Grav\Plugin\Console\DevToolsCommand::$grav in plugins://devtools/cli/../classes/DevToolsCommand.php on line 19

Help??

**Comment by flaviocopes** [comment]
Which version of Grav are you using?

**Comment by rhukster** [comment]
Fixed dev tools a while back. and wrong repo
